--Tạo DB
CREATE DATABASE BTVN1_QLBH
GO

USE BTVN1_QLBH 
GO

--Tạo table và khoá chính (Primary key - PK)
--DROP TABLE KhachHang
CREATE TABLE KHACHHANG
(
MAKH CHAR(4)PRIMARY KEY,
HOTEN VARCHAR(40),
DCHI VARCHAR(40),
SODT VARCHAR (20),
NGSINH SMALLDATETIME,
NGDK SMALLDATETIME,
DOANHSO MONEY,
)
GO

CREATE TABLE NHANVIEN
(
MANV CHAR(4)PRIMARY KEY,
HOTEN VARCHAR(40),
SODT VARCHAR (20),
NGVL SMALLDATETIME,
)
GO

--sửa tên NGVL thành NGLV
--sp_rename 'tên_bảng.tên_cột_cũ', 'tên_cột_mới', 'COLUMN';
/*ALTER TABLE [tên bảng] RENAME COLUMN [tên cột cũ] TO [tên cột mới]*/
sp_rename 'NHANVIEN.NGVL','NGLV', 'COLUMN'
CREATE TABLE  SANPHAM 
(
MASP CHAR(4)PRIMARY KEY,
TENSP VARCHAR(40),
DVT VARCHAR (20),
NUOCSX VARCHAR(40),
GIA MONEY,
)
GO

CREATE TABLE HOADON 
(
SOHD INT PRIMARY KEY,
NGHD SMALLDATETIME,
MAKH CHAR(4),
MANV CHAR(4),
TRIGIA MONEY,
)
GO

CREATE TABLE CTHD
(
SOHD INT,
MASP CHAR(4),
SL INT,
PRIMARY KEY (SOHD, MASP)
)
GO
