--tạo các khoá ngoại

-- Tạo khoá ngoại của bảng HD
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KH
FOREIGN KEY (MAKH)
REFERENCES KHACHHANG(MAKH)


-- Tạo khoá ngoại của bảng HD
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_NV
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
GO

-- Tạo khoá ngoại của bảng CTHD
ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HOADON
FOREIGN KEY (SOHD)
REFERENCES HOADON(SOHD)
GO

-- Tạo khoá ngoại của bảng CTHD
ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_SANPHAM
FOREIGN KEY (MASP)
REFERENCES SANPHAM(MASP)
GO
